// @flow
export const SPEECH = 'speech';

export const ACTION_TYPES = {
  DID_START_SPEECH_TRANSCRIPTION: `${SPEECH}.DID_START_SPEECH_TRANSCRIPTION`,
  DID_SUCCESSFULLY_START_SPEECH_TRANSCRIPTION: `${SPEECH}.DID_SUCCESSFULLY_START_SPEECH_TRANSCRIPTION`,
  DID_UNSUCCESSFULLY_START_SPEECH_TRANSCRIPTION: `${SPEECH}.DID_UNSUCCESSFULLY_START_SPEECH_TRANSCRIPTION`,
  DID_SUCCESSFULLY_RECEIVE_SPEECH_TRANSCRIPTION: `${SPEECH}.DID_SUCCESSFULLY_RECEIVE_SPEECH_TRANSCRIPTION`,
  DID_NOT_SUCCESSFULLY_RECEIVE_SPEECH_TRANSCRIPTION: `${SPEECH}.DID_NOT_SUCCESSFULLY_RECEIVE_SPEECH_TRANSCRIPTION`,
  DID_START_ENDING_SPEECH_TRANSCRIPTION: `${SPEECH}.DID_START_ENDING_SPEECH_TRANSCRIPTION`,
  DID_SUCCESSFULLY_END_SPEECH_TRANSCRIPTION: `${SPEECH}.DID_SUCCESSFULLY_END_SPEECH_TRANSCRIPTION`,
  DID_UNSUCCESSFULLY_END_SPEECH_TRANSCRIPTION: `${SPEECH}.DID_UNSUCCESSFULLY_END_SPEECH_TRANSCRIPTION`,
  WILL_SET_LOCALE: `${SPEECH}.WILL_SET_LOCALE`,
  DID_SET_LOCALE: `${SPEECH}.DID_SET_LOCALE`,
  DID_FAIL_TO_SET_LOCALE: `${SPEECH}.DID_FAIL_TO_SET_LOCALE`,
};
