// @flow
export const MEDIA = 'media';

export const ACTION_TYPES = {
  DID_START_SPEECH_TRANSCRIPTION: `${MEDIA}.DID_START_SPEECH_TRANSCRIPTION`,
  DID_SUCCESSFULLY_START_SPEECH_TRANSCRIPTION: `${MEDIA}.DID_SUCCESSFULLY_START_SPEECH_TRANSCRIPTION`,
  DID_UNSUCCESSFULLY_START_SPEECH_TRANSCRIPTION: `${MEDIA}.DID_UNSUCCESSFULLY_START_SPEECH_TRANSCRIPTION`,
  DID_SUCCESSFULLY_RECEIVE_SPEECH_TRANSCRIPTION: `${MEDIA}.DID_SUCCESSFULLY_RECEIVE_SPEECH_TRANSCRIPTION`,
  DID_NOT_SUCCESSFULLY_RECEIVE_SPEECH_TRANSCRIPTION: `${MEDIA}.DID_NOT_SUCCESSFULLY_RECEIVE_SPEECH_TRANSCRIPTION`,
  DID_START_ENDING_SPEECH_TRANSCRIPTION: `${MEDIA}.DID_START_ENDING_SPEECH_TRANSCRIPTION`,
  DID_SUCCESSFULLY_END_SPEECH_TRANSCRIPTION: `${MEDIA}.DID_SUCCESSFULLY_END_SPEECH_TRANSCRIPTION`,
  DID_UNSUCCESSFULLY_END_SPEECH_TRANSCRIPTION: `${MEDIA}.DID_UNSUCCESSFULLY_END_SPEECH_TRANSCRIPTION`,
};
