// @flow

export const DEVICE = 'device';

export const ACTION_TYPES = {
  DID_RECEIVE_APP_STATE_CHANGE: `${DEVICE}.DID_RECEIVE_APP_STATE_CHANGE`,
  DID_RECEIVE_DEVICE_INFO: `${DEVICE}.DID_RECEIVE_DEVICE_INFO`,
};
