// @flow
import { prefixWithModuleName } from '../utils';

export const MEDIA = 'media';

export const ACTION_TYPES = prefixWithModuleName(MEDIA, [
  'DID_START_LOADING_VIDEO_ASSETS',
  'DID_SUCCESSFULLY_LOAD_VIDEO_ASSETS',
  'DID_UNSUCCESSFULLY_LOAD_VIDEO_ASSETS',

  'DID_START_SPEECH_TRANSCRIPTION',
  'DID_SUCCESSFULLY_START_SPEECH_TRANSCRIPTION',
  'DID_UNSUCCESSFULLY_START_SPEECH_TRANSCRIPTION',

  'DID_SUCCESSFULLY_RECEIVE_SPEECH_TRANSCRIPTION',
  'DID_UNSUCCESSFULLY_RECEIVE_SPEECH_TRANSCRIPTION',
]);
