// @flow
export const MEDIA = 'media';

export const ACTION_TYPES = {
  DID_START_CAMERA_CAPTURE: `${MEDIA}.DID_START_CAMERA_CAPTURE`,
  DID_SUCCESSFULLY_START_CAMERA_CAPTURE: `${MEDIA}.DID_SUCCESSFULLY_START_CAMERA_CAPTURE`,
  DID_UNSUCCESSFULLY_START_CAMERA_CAPTURE: `${MEDIA}.DID_UNSUCCESSFULLY_START_CAMERA_CAPTURE`,
  DID_STOP_CAMERA_CAPTURE: `${MEDIA}.DID_STOP_CAMERA_CAPTURE`,
  DID_SUCCESSFULLY_STOP_CAMERA_CAPTURE: `${MEDIA}.DID_SUCCESSFULLY_STOP_CAMERA_CAPTURE`,
  DID_UNSUCCESSFULLY_STOP_CAMERA_CAPTURE: `${MEDIA}.DID_UNSUCCESSFULLY_STOP_CAMERA_CAPTURE`,
  DID_RECEIVE_FINISHED_VIDEO: `${MEDIA}.DID_RECEIVE_FINISHED_VIDEO`,
  WILL_EXPORT_VIDEO: `${MEDIA}.WILL_EXPORT_VIDEO`,
  DID_SUCCESSFULLY_EXPORT_VIDEO: `${MEDIA}.DID_SUCCESSFULLY_EXPORT_VIDEO`,
  DID_NOT_SUCCESSFULLY_EXPORT_VIDEO: `${MEDIA}.DID_NOT_SUCCESSFULLY_EXPORT_VIDEO`,
};
