// @flow
export const VIDEO = 'video';

export const ACTION_TYPES = {
  DID_RECEIVE_FONT_FAMILY: `${VIDEO}.DID_RECEIVE_FONT_FAMILY`,
  DID_RECEIVE_BACKGROUND_COLOR: `${VIDEO}.DID_RECEIVE_BACKGROUND_COLOR`,
  DID_RECEIVE_TEXT_COLOR: `${VIDEO}.DID_RECEIVE_TEXT_COLOR`,
  DID_RECEIVE_FONT_SIZE: `${VIDEO}.DID_RECEIVE_FONT_SIZE`,
};
